
project_id = "diadwozorwkzhexhjfgb"

[api]
port = 54321
schemes = ["http", "https"]
host = "127.0.0.1"

[[extends]]
file = "supabase/config.base.toml"

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[auth]
port = 54328

[meta]
port = 54329

[vector]
port = 54330

[realtime]
port = 54331

[functions.customer-history]
verify_jwt = true
